name: Deploy to production

on:
  push:
    branches: [main] # или release, если отдельный поток

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.21.3"

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR (private)
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Load secrets and save to app.env
        run: |
          aws secretsmanager get-secret-value --secret-id simple_bank \
            --query SecretString --output text \
            | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > app.env

      - name: Build, tag, and push Docker image to ECR
        env:
          ECR_REGISTRY: 160813693928.dkr.ecr.eu-central-1.amazonaws.com
          ECR_REPOSITORY: simplebank
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Building Docker image..."
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
                       -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          echo "Pushing Docker image..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # - name: Update kubeconfig for EKS
      #   run: aws eks update-kubeconfig --name simple-bank-eks --region eu-central-1

      # - name: Deploy to EKS
      #   run: |
      #     kubectl apply -f eks/aws-auth.yaml
      #     kubectl apply -f eks/deployment.yaml
      #     kubectl apply -f eks/service.yaml
      #     kubectl apply -f eks/issuer.yaml
      #     kubectl apply -f eks/ingress-nginx.yaml
      #     kubectl apply -f eks/ingress-http.yaml
      #     kubectl apply -f eks/ingress-grpc.yaml
